### ISSUE TITLE
getText stripps non html usage of gt/lt

### ISSUE THREAD

**Issue by MarkVaughn** [mtibben/html2text#108]
Is there a reason that non html uses of less than / greater than get stripped?

```
        $text = 'over 95% and very few financial penalties (<2%) lorem ipsum (KPI > 95%), major changes applied';
        $helper = new Html2Text($text);
        $this->assertContains('lorem ipsum', $helper->getText());
```

**Comment by vinnyusestrict** [comment]
It expects valid html, so you should convert the characters to entities.

`$text = 'over 95% and very few financial penalties (&lt;2%) lorem ipsum (KPI &gt; 95%), major changes applied';`
