### ISSUE TITLE
URLs are uppercased inside of b tags.

### ISSUE THREAD

**Issue by jpirkey** [mtibben/html2text#14]
URLs get uppercased when they are encapsulated by a bold tag: 
```html
<b><a href="https://www.tave.com/Test/LowerAndUpperCase?Signature=518d4bf6872e0deaf0eeb23b19c724514ec7c69a">Test</a></b>
```
becomes:
```html
TEST
[HTTPS://WWW.TAVE.COM/TEST/LOWERANDUPPERCASE?SIGNATURE=518D4BF6872E0DEAF0EEB23B19C724514EC7C69A]
```

In the call to `_preg_callback`, for the `b` and `strong` tags, we call `_toupper` of `$matches[3]`, but it doesn't look like `_toupper` handles when the link has already been parsed.  See test case below:

```php
$contents = '

<b><a href="https://www.tave.com/Test/LowerAndUpperCase?Signature=518d4bf6872e0deaf0eeb23b19c724514ec7c69a">Test</a></b>

<a href="https://www.tave.com/Test/LowerAndUpperCase?Signature=518d4bf6872e0deaf0eeb23b19c724514ec7c69a"><b>Test</b></a>

';

try {
  $textContents = new \Html2Text\Html2Text($contents);
  $textContents = $textContents->get_text();
}
catch (Exception $e) {
    return $e;
}

echo $textContents;

/* Result */
/*

TEST
[HTTPS://WWW.TAVE.COM/TEST/LOWERANDUPPERCASE?SIGNATURE=518D4BF6872E0DEAF0EEB23B19C724514EC7C69A]
TEST
[https://www.tave.com/Test/LowerAndUpperCase?Signature=518d4bf6872e0deaf0eeb23b19c724514ec7c69a]';

*/

```

`$matches[3]` will contain:
```
Test [https://www.tave.com/Test/LowerAndUpperCase?Signature=518d4bf6872e0deaf0eeb23b19c724514ec7c69a]
```

so `_toupper` doesn't have any tags to split on and blindly uppercases the whole string.

I'll look into doing a pull request for this, but I am in a bit of a time crunch right now, so I figured I would report it and see whomever got to it first.

Cheers

**Comment by mtibben** [comment]
I believe this has been fixed by https://github.com/mtibben/html2text/pull/30

If not, please create some test cases
