### ISSUE TITLE
&laquo and &raquo

### ISSUE THREAD

**Issue by johanovic** [mtibben/html2text#29]
These items are not changed into text (« and ») whilst they should be. These are often used in french as quotation marks.

**Comment by johanovic** [comment]
My mistake. I switched to using the python version of html2text which works just fine. This can be closed because my problem is solved (not because the issue is solved).

**Comment by mtibben** [comment]
works for me, and there is a testcase https://github.com/mtibben/html2text/blob/master/test/HtmlCharsTest.php#L9

**Comment by johanovic** [comment]
Maybe the problem is that is used it as `grep . 'something' | html2text`
