### ISSUE TITLE
Links format 'inline' and 'nextline'

### ISSUE THREAD

**Issue by eddi13** [mtibben/html2text#34]
If you, among other things, has such links in HTML
< a href="http://example.com/en/content/5/Some-Site.html" >http://example.com/en/content/5/Some-Site.html< /a >
these links are output as
http://example.com/en/content/5/Some-Site.html [http://example.com/en/content/5/Some-Site.html]
what is complet superfluous.

So it was with Jon Abernathy, it is also here.

Of course Flag 'none', but in this flag all links as $display (buildlinkList() line about 398) are output.

I fixed it with ever
return $display. "\ n ['. $ url. ']'; -> return $ display == $url ? $display : $display. "\n ['. $url. ']';
and
return $display. '['. $url. ']'; -> return $display == $url ? $display : $display. '['. $url. ']';
but I have to rub entire buildlinkList() in child class, which is not optimal course.

Can you perhaps add flags like 'inline_auto' and 'nextline_auto' that take into account such situations. Or in any other way can handle these situations.

**Comment by mtibben** [comment]
I don't have time to add features myself, but pull requests are welcome
