### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by sebawolf** [mtibben/html2text#37]
Hi!

It seems I have found a bug, I'm not sure about the reason, I tried replacing &lt;blockquote&gt; and &lt;/blockquote&gt; (using, for example, &lt;div&gt; and &lt;/div&gt;) and that fixed this particular case but after doing that I realized it's about the string length, I think the problem could be a "wrong" str_pos to replace something (???). I don't really know... Thoughts?

TEST CASE (I'm working with Tumblr API, this is just some text from a random post):

$test_str = "&lt;p&gt;Highlights from today&amp;rsquo;s &lt;strong&gt;Newlyhired Game&lt;/strong&gt;:&lt;/p&gt;&lt;blockquote&gt;&lt;p&gt;&lt;strong&gt;Sean:&lt;/strong&gt; What came first, Blake&amp;rsquo;s first &lt;em&gt;Chief Architect position&lt;/em&gt; or Blake&amp;rsquo;s first &lt;em&gt;girlfriend&lt;/em&gt;?&lt;/p&gt; &lt;/blockquote&gt; &lt;blockquote&gt; &lt;p&gt;&lt;strong&gt;Sean:&lt;/strong&gt; Devin, Bryan spent almost five years of his life slaving away for this vampire squid wrapped around the face of humanity&amp;hellip;&lt;br/&gt;&lt;strong&gt;Devin:&lt;/strong&gt; Goldman Sachs?&lt;br/&gt;&lt;strong&gt;Sean:&lt;/strong&gt; Correct!&lt;/p&gt; &lt;/blockquote&gt; &lt;blockquote&gt; &lt;p&gt;&lt;strong&gt;Sean:&lt;/strong&gt; What was the name of the girl Zhu took to prom three months ago?&lt;br/&gt;&lt;strong&gt;John:&lt;/strong&gt; What?&lt;br/&gt;&lt;strong&gt;Derek (from the audience):&lt;/strong&gt; Destiny!&lt;br/&gt;&lt;strong&gt;Zhu:&lt;/strong&gt; Her name is Jolene. She&amp;rsquo;s nice. I like her.&lt;/p&gt;&lt;/blockquote&gt;&lt;p&gt;I think the audience is winning.&amp;nbsp; - Derek&lt;/p&gt;";

$html2text = new \Html2Text\Html2Text($test_str);
echo $html2text->getText();

Thanks for you help!

Cheers,
              Sebatian C.

**Comment by dsas** [comment]
I've got a test case for this in dsas/html2text@82692b5beca2274cbb637f81c8740827d12c961d

**Comment by voku** [comment]
```$diff = $len ...```
-> 
```$diff += $len ... ```

e.g.: https://github.com/voku/html2text/commit/751811b7ffcb7d1c9d81a0c885b038ade95c7504
