### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by andrewnicols** [mtibben/html2text#51]
Hi,

Any chance of a new release for the library? The last release was 3.0.0 in October, and since then there have been a range of bug fixes and new features, including:
#44 PHP7 support in unit tests
#37/#45 blockquote parsing fix
#7 Treat all paragraph content equally
#47 bbcode support

We (moodle/moodle) can pull from master, but generally we prefer to pick known releases.

Thanks in advance,

Andrew

**Comment by mtibben** [comment]
Yep no probs, getting a release together now

**Comment by mtibben** [comment]
Released 3.1.0 and 4.0.0

**Comment by mtibben** [comment]
@andrewnicols I've given you push access to the repo, as it seems like you're a major consumer of this library and your contributions have been of high quality

**Comment by andrewnicols** [comment]
Thanks - much obliged :)
