### ISSUE TITLE
This vs https://github.com/soundasleep/html2text

### ISSUE THREAD

**Issue by giorgio79** [mtibben/html2text#54]
What are the differences between this repo and this one https://github.com/soundasleep/html2text

**Comment by mtibben** [comment]
Looks like that uses the DOM rather than regexes, Frankly it's a much better approach

**Comment by laticrete-pimcore** [comment]
Is the comparison between this library and https://github.com/soundasleep/html2text still valid? 

What are the pros / cons of the two libraries / approaches?
