### ISSUE TITLE
'&nbsp;' convert

### ISSUE THREAD

**Issue by eddi13** [mtibben/html2text#55]
```
$htmlToText = new \Html2Text\Html2Text('&nbsp;');
var_dump(trim($htmlToText->getText())); //string(2) " "
```
as I understand it should be string(0) ""

best regards, Eduard

**Comment by andrewnicols** [comment]
Hi,

Actually non-breaking white space is not trimmed. If you inspect the character produced you'll find that it's a literal non breaking space.

This is the correct behaviour,

Andrew

**Comment by eddi13** [comment]
Hi.
```
$htmlToText = new \Html2Text\Html2Text("&nbsp;");
var_dump(trim($htmlToText->getText(), "\xC2\xA0"));//string(0) ""
```
It works, thanks
best regards, Eduard
