### ISSUE TITLE
Multibyte strings do not play nicely with blockquotes

### ISSUE THREAD

**Issue by cameron1729** [mtibben/html2text#57]
A string such as:

```
“Hello”

<blockquote>goodbye</blockquote>
```

Currently gets converted to:

```
“Hello”
```

This is because `mb_substr` in `convertBlockquotes` is truncating in the wrong place, which results in potentially incomplete `blockquote` tags, which `strip_tags` will remove.

I've created pull request #56 to address this.

**Comment by mtibben** [comment]
Merged #56
