### ISSUE TITLE
Inconsistent output with <br> tag within <pre> tag

### ISSUE THREAD

**Issue by cameron1729** [mtibben/html2text#60]
Consider this HTML:

```html
<pre>
    <span>
void FillMeUp(char* in_string) {<br />  int i = 0;<br />  while (in_string[i] != \'\0\') {<br />    in_string[i] = \'X\';<br />    i++;<br />  }<br />}
    </span>
</pre>
```

In version 3 it was rendered like this:

```
void FillMeUp(char* in_string) {
  int i = 0;
  while (in_string[i] != \'\') {
    in_string[i] = \'X\';
    i++;
  }
}
```

But now in version 4 we get this:

```
void FillMeUp(char* in_string) {
int i = 0;
while (in_string[i] != \'\') {
in_string[i] = \'X\';
i++;
}
}
```

As best I can tell this has something to do with the changes to the `callbackSearch` array - specifically the <br> addition.

**Comment by mtibben** [comment]
Do you know where the change occurred @cameron1729?  What would be the most correct behaviour?

**Comment by cameron1729** [comment]
Hey @mtibben I just had a discussion with @andrewnicols - I will hopefully be able to come up with a branch for you.

I believe this problem was introduced in [0d409337 ](https://github.com/cameron1729/html2text/commit/0d409337e10f90b4145bd286d11940a612fe1d91#diff-1ec09715b151c3f2cbeb43b5be65503cR137)- the regex for `<br>` in `callbackSearch` is matchin the "br" and all the whitespace after it.

**Comment by mtibben** [comment]
Yep go for it

**Comment by cameron1729** [comment]
Created #62
