### ISSUE TITLE
Mailto encoded with html entities get slash at the begining

### ISSUE THREAD

**Issue by jcubic** [mtibben/html2text#64]
On github profile there is urls like this:
```
&#109;&#97;&#105;&#108;&#116;&#111;&#58;%6a%63%75%62%69%63@%6a%63%75%62%69%63.%70%6c
```
which is mailto:email and html2text display that url as (if decoded):
```
[/mailto:%6a%63%75%62%69%63@%6a%63%75%62%69%63.%70%6c]
```
it add superfluous slash at the begining.

**Comment by mtibben** [comment]
Sorry, I'm not following. Can you provide a more complete explanation in https://github.com/mtibben/html2text/pull/66
