### ISSUE TITLE
Replacement for newlines and tabs

### ISSUE THREAD

**Issue by Goram** [mtibben/html2text#7]
Hi,

ist the " " as replacement correct? Newlines and tabs don´t do much in html. 

The html I have:

```
 <p>
    This is some text<br/>
    with a break in the middle
 </p>
```

Results to:

<pre>
This is some text
 with a break in the middle
</pre>

The " " before "with" is not correct there, but I can´t decide if there aren´t any other side effects?

**Comment by anedisi** [comment]
will this be merged ?
its kinda silly problem but its annoying. ?

**Comment by andrewnicols** [comment]
This behaviour gets my -1, or at least the unit test does.
There should be no difference between:
```
<p>Foo</p>
```
and
```
<p>
    Foo
</p>
```

These are both syntactically identical as far as HTML is concerned, and the Html2Text conversion should also yield identical results. If this were a ```<pre>``` tag, that would be different, but it isn't.

That said, I do feel that there is still a bug. That is to say that:
```
<p>
    Foo<br/>
    Bar
</p>
<p>
    Foo<br/>
    Bar
</p>
<p>Foo<br/>Bar</p>
```
Should all output identically:
```
Foo
Bar

Foo
Bar

Foo
Bar
```

So I see two bugs at play here:
1. leading whitespace is respected incorrectly in paragraph tags; and
1. Whitespace is incorrectly added at the _end_ of a paragraph tag
