### ISSUE TITLE
Use in Drupal?

### ISSUE THREAD

**Issue by Berdir** [mtibben/html2text#73]
Hi

The swiftmailer contrib module has been using this for a while now, and I opened an issue to remove our own custom html 2 text conversion in favor of this: https://www.drupal.org/node/2830384

Could be a bit tricky as our implementation apparently has different opinions on *everything*.

Even if we end up not doing that, I imagine that the issue might be useful for you to follow. We do have a decent amount of tests, quite possible that we not only see a difference of opinion in the failing tests but actual bugs in this library?

**Comment by mtibben** [comment]
Hi @Berdir, happy to receive PRs to help ease the transition
