### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by BenParizek** [mtibben/html2text#86]
You note in your README that a number of projects have found this useful and state "Now it has been extracted as a standalone library. Hopefully it can be of use to others.".

We're currently testing this out in a small, commercial software product we develop as well, and it's always nice to be sure that the libraries we are using support the right type of license so we don't cross any lines we shouldn't be crossing.

Would you be comfortable adding an open source license, like the MIT license or something (https://choosealicense.com), so it's clear how you allow others to use the codebase?

**Comment by andrewnicols** [comment]
Hi Ben,

This code is already licensed under the GPLv2. Will that not suffice?

**Comment by BenParizek** [comment]
Or, maybe not. GPL may require my product is also GPL, which it is not.

**Comment by mtibben** [comment]
See https://github.com/mtibben/html2text/blob/master/src/Html2Text.php#L3-L18 , feel free to PR to extract this into it's own LICENSE file
