### ISSUE TITLE
Doctrine Annotation Exception with "@type" on using html2text class

### ISSUE THREAD

**Issue by kanow** [mtibben/html2text#96]
Hi,

I use htm2text in a TYPO3 9.5 instance and PHP 7.2.21. On using html2Text class I have this exception in frontend:
```
(1/1) Doctrine\Common\Annotations\AnnotationException
[Semantical Error] The annotation "@type" in property Html2Text\Html2Text::$html was never imported. Did you maybe forget to add a "use" statement for this annotation?
```
TYPO3 is installed with composer. I'm using the "doctrine/annotations" v1.8.0 package.

Changing all "@type" to "@var" in "html2text/html2text/src/Html2Text.php" annotations solves the problem and the frontend shows me the plain text result. 

It would be fine, if that will be fixed.

**Comment by mtibben** [comment]
Fixed in #93

**Comment by kanow** [comment]
Thx, I will try the new version if I had to do other updates on that project. Probably that will take some time  ;-).

**Comment by kanow** [comment]
Hi, today I tested the new Version. Sorry for taking this a long time. New version works fine ;-). No error. thx.
